param(
  [ValidateSet("basic", "lint", "synth", "timing", "all")]
  [string]$Suite = "basic",

  [string]$Top = "rv32i_cached_ahb_master_top",
  [string]$Filelist = "sim/filelist.f",
  [string]$SdcFile = "project/constraints/rv32i_cached_ahb_master_top.sdc",
  [string]$LogRoot = "project/log/quality",

  [switch]$DryRun,
  [switch]$StrictTools
)

$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = Resolve-Path (Join-Path $ScriptDir "../..")
$SimDir = Join-Path $RepoRoot "sim"
$RunStamp = Get-Date -Format "yyyyMMdd_HHmmss"
$RunDir = Join-Path (Join-Path $RepoRoot $LogRoot) "$RunStamp-$Suite"

New-Item -ItemType Directory -Force $RunDir | Out-Null
Set-Location $RepoRoot

$summary = New-Object System.Collections.Generic.List[string]

function Add-Summary {
  param([string]$Line)
  $summary.Add($Line) | Out-Null
  Write-Host $Line
}

function Resolve-RepoPath {
  param([string]$Path)

  if ([System.IO.Path]::IsPathRooted($Path)) {
    return (Resolve-Path $Path).Path
  }
  return (Resolve-Path (Join-Path $RepoRoot $Path)).Path
}

function Get-QualityFilelist {
  param([string]$FilelistPath)

  $rtlFiles = New-Object System.Collections.Generic.List[string]
  $incDirs = New-Object System.Collections.Generic.List[string]
  $seenFilelists = @{}

  function Parse-Filelist {
    param([string]$Path)

    $fullPath = Resolve-RepoPath $Path
    if ($seenFilelists.ContainsKey($fullPath)) {
      return
    }
    $seenFilelists[$fullPath] = $true

    foreach ($rawLine in Get-Content -Encoding UTF8 $fullPath) {
      $line = ($rawLine -split "#", 2)[0].Trim()
      if ($line.Length -eq 0) {
        continue
      }

      if ($line -match "^-f\s+(.+)$") {
        $nested = $Matches[1].Trim()
        $nestedPath = if ([System.IO.Path]::IsPathRooted($nested)) {
          $nested
        } else {
          Join-Path $SimDir $nested
        }
        if (!(Test-Path -LiteralPath $nestedPath)) {
          throw "Missing nested filelist: $nestedPath"
        }
        Parse-Filelist $nestedPath
        continue
      }

      if ($line -match "^\+incdir\+(.+)$") {
        $inc = $Matches[1].Trim()
        $incPath = if ([System.IO.Path]::IsPathRooted($inc)) {
          $inc
        } else {
          Join-Path $SimDir $inc
        }
        if (!(Test-Path -LiteralPath $incPath -PathType Container)) {
          throw "Missing include directory: $incPath"
        }
        $incDirs.Add((Resolve-Path $incPath).Path) | Out-Null
        continue
      }

      if ($line.StartsWith("+")) {
        continue
      }

      $srcPath = if ([System.IO.Path]::IsPathRooted($line)) {
        $line
      } else {
        Join-Path $SimDir $line
      }
      if (!(Test-Path -LiteralPath $srcPath -PathType Leaf)) {
        throw "Missing RTL source: $srcPath"
      }
      $rtlFiles.Add((Resolve-Path $srcPath).Path) | Out-Null
    }
  }

  Parse-Filelist $FilelistPath

  return [PSCustomObject]@{
    RtlFiles = $rtlFiles
    IncDirs = $incDirs
  }
}

function Get-RepoRelativePath {
  param([string]$Path)

  $full = (Resolve-Path $Path).Path
  $root = $RepoRoot.Path.TrimEnd("\", "/") + [System.IO.Path]::DirectorySeparatorChar
  if ($full.StartsWith($root)) {
    return $full.Substring($root.Length).Replace("\", "/")
  }
  return $full.Replace("\", "/")
}

function Invoke-ExternalCommand {
  param(
    [string]$Name,
    [string]$Tool,
    [string[]]$Args,
    [string]$LogFile,
    [string]$WorkingDirectory = $RepoRoot
  )

  $cmdLine = "$Tool " + ($Args -join " ")
  if ($DryRun) {
    Add-Summary "[DRYRUN] ${Name}: $cmdLine"
    return
  }

  Add-Summary "[RUN] $Name"
  Push-Location $WorkingDirectory
  try {
    & $Tool @Args *> $LogFile
    if ($LASTEXITCODE -ne 0) {
      throw "$Name failed with exit code $LASTEXITCODE. Log: $LogFile"
    }
  } finally {
    Pop-Location
  }
  Add-Summary "[PASS] $Name log=$LogFile"
}

function Write-YosysScript {
  param(
    [string]$OutPath,
    [string]$TopModule,
    [System.Collections.Generic.List[string]]$RtlFiles
  )

  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add("# Generated by tools/quality/run_quality_checks.ps1") | Out-Null
  $lines.Add("read_verilog -sv -DSYNTHESIS -I rtl/include \") | Out-Null

  for ($i = 0; $i -lt $RtlFiles.Count; $i = $i + 1) {
    $rel = Get-RepoRelativePath $RtlFiles[$i]
    $suffix = if ($i -eq ($RtlFiles.Count - 1)) { "" } else { " \" }
    $lines.Add("  $rel$suffix") | Out-Null
  }

  $lines.Add("hierarchy -check -top $TopModule") | Out-Null
  $lines.Add("proc") | Out-Null
  $lines.Add("opt") | Out-Null
  $lines.Add("check") | Out-Null
  $lines.Add("synth -top $TopModule") | Out-Null
  $lines.Add("stat") | Out-Null
  Set-Content -Encoding UTF8 -Path $OutPath -Value $lines
}

$qualityFilelist = Get-QualityFilelist $Filelist
$filelistReport = Join-Path $RunDir "filelist_sources.txt"
$qualityFilelist.RtlFiles | ForEach-Object { Get-RepoRelativePath $_ } | Set-Content -Encoding UTF8 $filelistReport
Add-Summary "[PASS] filelist: $($qualityFilelist.RtlFiles.Count) RTL files, $($qualityFilelist.IncDirs.Count) include dirs"

$resolvedSdc = Resolve-RepoPath $SdcFile
if (Test-Path -LiteralPath $resolvedSdc -PathType Leaf) {
  Add-Summary "[PASS] timing constraint exists: $(Get-RepoRelativePath $resolvedSdc)"
} else {
  throw "Missing SDC file: $resolvedSdc"
}

if ($Suite -eq "basic") {
  $summary | Set-Content -Encoding UTF8 (Join-Path $RunDir "summary.txt")
  exit 0
}

if (($Suite -eq "lint") -or ($Suite -eq "all")) {
  $verilator = Get-Command verilator -ErrorAction SilentlyContinue
  if ($null -eq $verilator) {
    if ($StrictTools) {
      throw "Missing optional tool: verilator"
    }
    Add-Summary "[SKIP] verilator lint: missing verilator"
  } else {
    $args = @(
      "--lint-only",
      "-Wall",
      "-Wno-DECLFILENAME",
      "-Wno-UNUSED",
      "-Wno-UNDRIVEN",
      "-Wno-WIDTH",
      "-Wno-CASEINCOMPLETE",
      "--top-module", $Top,
      "-f", "filelist.f"
    )
    Invoke-ExternalCommand "verilator lint" $verilator.Source $args (Join-Path $RunDir "verilator_lint.log") $SimDir
  }
}

if (($Suite -eq "synth") -or ($Suite -eq "all")) {
  $yosys = Get-Command yosys -ErrorAction SilentlyContinue
  $yosysScript = Join-Path $RunDir "yosys_synth.ys"
  Write-YosysScript $yosysScript $Top $qualityFilelist.RtlFiles

  if ($null -eq $yosys) {
    if ($StrictTools) {
      throw "Missing optional tool: yosys"
    }
    Add-Summary "[SKIP] yosys synth: missing yosys; generated $(Get-RepoRelativePath $yosysScript)"
  } else {
    $args = @("-s", (Get-RepoRelativePath $yosysScript))
    Invoke-ExternalCommand "yosys synth/check" $yosys.Source $args (Join-Path $RunDir "yosys_synth.log") $RepoRoot
  }
}

if (($Suite -eq "timing") -or ($Suite -eq "all")) {
  $sta = Get-Command sta -ErrorAction SilentlyContinue
  if ($null -eq $sta) {
    Add-Summary "[SKIP] opensta timing: missing sta; SDC syntax/template check only"
  } else {
    Add-Summary "[SKIP] opensta timing: sta exists, but no liberty/netlist is configured yet"
  }
}

$summary | Set-Content -Encoding UTF8 (Join-Path $RunDir "summary.txt")
