#!/usr/bin/env bash
set -euo pipefail

suite="basic"
top="rv32i_cached_ahb_master_top"
filelist="sim/filelist.f"
sdc_file="project/constraints/rv32i_cached_ahb_master_top.sdc"
log_root="project/log/quality"
dry_run=0
strict_tools=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --suite)
      suite="$2"
      shift 2
      ;;
    --top)
      top="$2"
      shift 2
      ;;
    --filelist)
      filelist="$2"
      shift 2
      ;;
    --sdc)
      sdc_file="$2"
      shift 2
      ;;
    --log-root)
      log_root="$2"
      shift 2
      ;;
    --dry-run)
      dry_run=1
      shift
      ;;
    --strict-tools)
      strict_tools=1
      shift
      ;;
    -h|--help)
      cat <<'USAGE'
Usage: tools/quality/run_quality_checks.sh [options]

Options:
  --suite basic|lint|synth|timing|all
  --top <top-module>
  --filelist <filelist>
  --sdc <sdc-file>
  --log-root <dir>
  --dry-run
  --strict-tools
USAGE
      exit 0
      ;;
    *)
      echo "ERROR: unknown option: $1" >&2
      exit 2
      ;;
  esac
done

case "$suite" in
  basic|lint|synth|timing|all) ;;
  *)
    echo "ERROR: invalid suite: $suite" >&2
    exit 2
    ;;
esac

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/../.." && pwd)"
sim_dir="$repo_root/sim"
run_stamp="$(date +%Y%m%d_%H%M%S)"
run_dir="$repo_root/$log_root/$run_stamp-$suite"
mkdir -p "$run_dir"
cd "$repo_root"

summary_file="$run_dir/summary.txt"
: > "$summary_file"
rtl_files=()
inc_dirs=()
seen_filelists=" "

add_summary() {
  echo "$1" | tee -a "$summary_file"
}

resolve_from_repo() {
  local path="$1"
  if [[ "$path" = /* ]]; then
    echo "$path"
  else
    echo "$repo_root/$path"
  fi
}

repo_relative() {
  local full="$1"
  full="$(cd "$(dirname "$full")" && pwd)/$(basename "$full")"
  printf '%s\n' "${full#$repo_root/}"
}

parse_filelist() {
  local path="$1"
  local full
  full="$(resolve_from_repo "$path")"
  full="$(cd "$(dirname "$full")" && pwd)/$(basename "$full")"

  if [[ "$seen_filelists" == *" $full "* ]]; then
    return
  fi
  seen_filelists="$seen_filelists$full "

  while IFS= read -r raw_line || [[ -n "$raw_line" ]]; do
    local line nested nested_path inc inc_path src_path
    line="${raw_line%%#*}"
    line="$(printf '%s' "$line" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"
    [[ -z "$line" ]] && continue

    if [[ "$line" =~ ^-f[[:space:]]+(.+)$ ]]; then
      nested="${BASH_REMATCH[1]}"
      if [[ "$nested" = /* ]]; then
        nested_path="$nested"
      else
        nested_path="$sim_dir/$nested"
      fi
      [[ -f "$nested_path" ]] || { echo "ERROR: missing nested filelist: $nested_path" >&2; exit 1; }
      parse_filelist "$nested_path"
      continue
    fi

    if [[ "$line" =~ ^\+incdir\+(.+)$ ]]; then
      inc="${BASH_REMATCH[1]}"
      if [[ "$inc" = /* ]]; then
        inc_path="$inc"
      else
        inc_path="$sim_dir/$inc"
      fi
      [[ -d "$inc_path" ]] || { echo "ERROR: missing include directory: $inc_path" >&2; exit 1; }
      inc_dirs+=("$(cd "$inc_path" && pwd)")
      continue
    fi

    if [[ "$line" == +* ]]; then
      continue
    fi

    if [[ "$line" = /* ]]; then
      src_path="$line"
    else
      src_path="$sim_dir/$line"
    fi
    [[ -f "$src_path" ]] || { echo "ERROR: missing RTL source: $src_path" >&2; exit 1; }
    rtl_files+=("$(cd "$(dirname "$src_path")" && pwd)/$(basename "$src_path")")
  done < "$full"
}

write_yosys_script() {
  local out="$1"
  {
    echo "# Generated by tools/quality/run_quality_checks.sh"
    printf 'read_verilog -sv -DSYNTHESIS -I rtl/include'
    local file
    for file in "${rtl_files[@]}"; do
      printf ' \\\n  %s' "$(repo_relative "$file")"
    done
    printf '\n'
    echo "hierarchy -check -top $top"
    echo "proc"
    echo "opt"
    echo "check"
    echo "synth -top $top"
    echo "stat"
  } > "$out"
}

run_external() {
  local name="$1"
  local workdir="$2"
  local logfile="$3"
  shift 3

  if [[ "$dry_run" -eq 1 ]]; then
    add_summary "[DRYRUN] $name: $*"
    return
  fi

  add_summary "[RUN] $name"
  (cd "$workdir" && "$@") > "$logfile" 2>&1
  add_summary "[PASS] $name log=$logfile"
}

parse_filelist "$filelist"
for file in "${rtl_files[@]}"; do
  repo_relative "$file"
done > "$run_dir/filelist_sources.txt"

add_summary "[PASS] filelist: ${#rtl_files[@]} RTL files, ${#inc_dirs[@]} include dirs"

resolved_sdc="$(resolve_from_repo "$sdc_file")"
[[ -f "$resolved_sdc" ]] || { echo "ERROR: missing SDC file: $resolved_sdc" >&2; exit 1; }
add_summary "[PASS] timing constraint exists: $(repo_relative "$resolved_sdc")"

if [[ "$suite" == "basic" ]]; then
  exit 0
fi

if [[ "$suite" == "lint" || "$suite" == "all" ]]; then
  if ! command -v verilator >/dev/null 2>&1; then
    if [[ "$strict_tools" -eq 1 ]]; then
      echo "ERROR: missing optional tool: verilator" >&2
      exit 1
    fi
    add_summary "[SKIP] verilator lint: missing verilator"
  else
    run_external "verilator lint" "$sim_dir" "$run_dir/verilator_lint.log" \
      verilator --lint-only -Wall \
      -Wno-DECLFILENAME -Wno-UNUSED -Wno-UNDRIVEN -Wno-WIDTH -Wno-CASEINCOMPLETE \
      --top-module "$top" -f filelist.f
  fi
fi

if [[ "$suite" == "synth" || "$suite" == "all" ]]; then
  yosys_script="$run_dir/yosys_synth.ys"
  write_yosys_script "$yosys_script"

  if ! command -v yosys >/dev/null 2>&1; then
    if [[ "$strict_tools" -eq 1 ]]; then
      echo "ERROR: missing optional tool: yosys" >&2
      exit 1
    fi
    add_summary "[SKIP] yosys synth: missing yosys; generated $(repo_relative "$yosys_script")"
  else
    run_external "yosys synth/check" "$repo_root" "$run_dir/yosys_synth.log" \
      yosys -s "$(repo_relative "$yosys_script")"
  fi
fi

if [[ "$suite" == "timing" || "$suite" == "all" ]]; then
  if ! command -v sta >/dev/null 2>&1; then
    add_summary "[SKIP] opensta timing: missing sta; SDC syntax/template check only"
  else
    add_summary "[SKIP] opensta timing: sta exists, but no liberty/netlist is configured yet"
  fi
fi
