module rv32i_ahb_matrix_soc_top #(
  parameter ICACHE_INDEX_BITS = 2,
  parameter DCACHE_INDEX_BITS = 2,
  parameter [31:0] RESET_PC = 32'h0800_0000,
  parameter BRANCH_PRED_INDEX_BITS = 6
) (
  input  wire        clk,
  input  wire        rst_n,
  input  wire        timer_irq,

  output wire        flash_hsel,
  output wire [31:0] flash_haddr,
  output wire [2:0]  flash_hburst,
  output wire [3:0]  flash_hprot,
  output wire [2:0]  flash_hsize,
  output wire [1:0]  flash_htrans,
  output wire [31:0] flash_hwdata,
  output wire        flash_hwrite,
  output wire        flash_hready,
  input  wire [31:0] flash_hrdata,
  input  wire        flash_hreadyout,
  input  wire [1:0]  flash_hresp,

  output wire        sram_hsel,
  output wire [31:0] sram_haddr,
  output wire [2:0]  sram_hburst,
  output wire [3:0]  sram_hprot,
  output wire [2:0]  sram_hsize,
  output wire [1:0]  sram_htrans,
  output wire [31:0] sram_hwdata,
  output wire        sram_hwrite,
  output wire        sram_hready,
  input  wire [31:0] sram_hrdata,
  input  wire        sram_hreadyout,
  input  wire [1:0]  sram_hresp,

  output wire        ahb_periph_hsel,
  output wire [31:0] ahb_periph_haddr,
  output wire [2:0]  ahb_periph_hburst,
  output wire [3:0]  ahb_periph_hprot,
  output wire [2:0]  ahb_periph_hsize,
  output wire [1:0]  ahb_periph_htrans,
  output wire [31:0] ahb_periph_hwdata,
  output wire        ahb_periph_hwrite,
  output wire        ahb_periph_hready,
  input  wire [31:0] ahb_periph_hrdata,
  input  wire        ahb_periph_hreadyout,
  input  wire [1:0]  ahb_periph_hresp,

  output wire        apb_periph_hsel,
  output wire [31:0] apb_periph_haddr,
  output wire [2:0]  apb_periph_hburst,
  output wire [3:0]  apb_periph_hprot,
  output wire [2:0]  apb_periph_hsize,
  output wire [1:0]  apb_periph_htrans,
  output wire [31:0] apb_periph_hwdata,
  output wire        apb_periph_hwrite,
  output wire        apb_periph_hready,
  input  wire [31:0] apb_periph_hrdata,
  input  wire        apb_periph_hreadyout,
  input  wire [1:0]  apb_periph_hresp,

  output wire [31:0] dbg_pc,
  output wire [31:0] dbg_cycle,
  output wire [31:0] dbg_instret,
  output wire [31:0] dbg_stall_cycle,
  output wire [31:0] dbg_flush_cycle,
  output wire [31:0] dbg_branch_count,
  output wire [31:0] dbg_branch_mispredict_count,
  output wire [31:0] dbg_btb_hit_count,
  output wire [31:0] dbg_btb_miss_count,
  output wire [31:0] dbg_bht_update_count,
  input  wire [4:0]  dbg_reg_addr,
  output wire [31:0] dbg_reg_rdata,
  output wire        dbg_illegal_instr,
  output wire        dbg_ecall,
  output wire        dbg_ebreak,

  output wire [31:0] dbg_icache_hit_count,
  output wire [31:0] dbg_icache_miss_count,
  output wire [31:0] dbg_dcache_hit_count,
  output wire [31:0] dbg_dcache_miss_count,
  output wire [31:0] dbg_bus_i_grant_count,
  output wire [31:0] dbg_bus_d_grant_count,
  output wire        dbg_cpu_bus_error,
  output wire        dbg_matrix_decode_error
);

  wire [31:0] cpu_haddr;
  wire [2:0]  cpu_hburst;
  wire [3:0]  cpu_hprot;
  wire [2:0]  cpu_hsize;
  wire [1:0]  cpu_htrans;
  wire [31:0] cpu_hwdata;
  wire        cpu_hwrite;
  wire [31:0] cpu_hrdata;
  wire        cpu_hready;
  wire [1:0]  cpu_hresp;

  rv32i_cached_ahb_master_top #(
    .ICACHE_INDEX_BITS(ICACHE_INDEX_BITS),
    .DCACHE_INDEX_BITS(DCACHE_INDEX_BITS),
    .RESET_PC(RESET_PC),
    .BRANCH_PRED_INDEX_BITS(BRANCH_PRED_INDEX_BITS)
  ) u_cpu (
    .clk                    (clk),
    .rst_n                  (rst_n),
    .timer_irq              (timer_irq),
    .ahb_haddr              (cpu_haddr),
    .ahb_hburst             (cpu_hburst),
    .ahb_hprot              (cpu_hprot),
    .ahb_hsize              (cpu_hsize),
    .ahb_htrans             (cpu_htrans),
    .ahb_hwdata             (cpu_hwdata),
    .ahb_hwrite             (cpu_hwrite),
    .ahb_hrdata             (cpu_hrdata),
    .ahb_hready             (cpu_hready),
    .ahb_hresp              (cpu_hresp),
    .dbg_pc                 (dbg_pc),
    .dbg_cycle              (dbg_cycle),
    .dbg_instret            (dbg_instret),
    .dbg_stall_cycle        (dbg_stall_cycle),
    .dbg_flush_cycle        (dbg_flush_cycle),
    .dbg_branch_count       (dbg_branch_count),
    .dbg_branch_mispredict_count(dbg_branch_mispredict_count),
    .dbg_btb_hit_count      (dbg_btb_hit_count),
    .dbg_btb_miss_count     (dbg_btb_miss_count),
    .dbg_bht_update_count   (dbg_bht_update_count),
    .dbg_reg_addr           (dbg_reg_addr),
    .dbg_reg_rdata          (dbg_reg_rdata),
    .dbg_illegal_instr      (dbg_illegal_instr),
    .dbg_ecall              (dbg_ecall),
    .dbg_ebreak             (dbg_ebreak),
    .dbg_icache_hit_count   (dbg_icache_hit_count),
    .dbg_icache_miss_count  (dbg_icache_miss_count),
    .dbg_dcache_hit_count   (dbg_dcache_hit_count),
    .dbg_dcache_miss_count  (dbg_dcache_miss_count),
    .dbg_bus_i_grant_count  (dbg_bus_i_grant_count),
    .dbg_bus_d_grant_count  (dbg_bus_d_grant_count),
    .dbg_bus_error          (dbg_cpu_bus_error)
  );

  rv32i_ahb_lite_matrix_1m4s u_matrix (
    .clk              (clk),
    .rst_n            (rst_n),
    .m_haddr          (cpu_haddr),
    .m_hburst         (cpu_hburst),
    .m_hprot          (cpu_hprot),
    .m_hsize          (cpu_hsize),
    .m_htrans         (cpu_htrans),
    .m_hwdata         (cpu_hwdata),
    .m_hwrite         (cpu_hwrite),
    .m_hrdata         (cpu_hrdata),
    .m_hready         (cpu_hready),
    .m_hresp          (cpu_hresp),
    .s0_hsel          (flash_hsel),
    .s0_haddr         (flash_haddr),
    .s0_hburst        (flash_hburst),
    .s0_hprot         (flash_hprot),
    .s0_hsize         (flash_hsize),
    .s0_htrans        (flash_htrans),
    .s0_hwdata        (flash_hwdata),
    .s0_hwrite        (flash_hwrite),
    .s0_hready        (flash_hready),
    .s0_hrdata        (flash_hrdata),
    .s0_hreadyout     (flash_hreadyout),
    .s0_hresp         (flash_hresp),
    .s1_hsel          (sram_hsel),
    .s1_haddr         (sram_haddr),
    .s1_hburst        (sram_hburst),
    .s1_hprot         (sram_hprot),
    .s1_hsize         (sram_hsize),
    .s1_htrans        (sram_htrans),
    .s1_hwdata        (sram_hwdata),
    .s1_hwrite        (sram_hwrite),
    .s1_hready        (sram_hready),
    .s1_hrdata        (sram_hrdata),
    .s1_hreadyout     (sram_hreadyout),
    .s1_hresp         (sram_hresp),
    .s2_hsel          (ahb_periph_hsel),
    .s2_haddr         (ahb_periph_haddr),
    .s2_hburst        (ahb_periph_hburst),
    .s2_hprot         (ahb_periph_hprot),
    .s2_hsize         (ahb_periph_hsize),
    .s2_htrans        (ahb_periph_htrans),
    .s2_hwdata        (ahb_periph_hwdata),
    .s2_hwrite        (ahb_periph_hwrite),
    .s2_hready        (ahb_periph_hready),
    .s2_hrdata        (ahb_periph_hrdata),
    .s2_hreadyout     (ahb_periph_hreadyout),
    .s2_hresp         (ahb_periph_hresp),
    .s3_hsel          (apb_periph_hsel),
    .s3_haddr         (apb_periph_haddr),
    .s3_hburst        (apb_periph_hburst),
    .s3_hprot         (apb_periph_hprot),
    .s3_hsize         (apb_periph_hsize),
    .s3_htrans        (apb_periph_htrans),
    .s3_hwdata        (apb_periph_hwdata),
    .s3_hwrite        (apb_periph_hwrite),
    .s3_hready        (apb_periph_hready),
    .s3_hrdata        (apb_periph_hrdata),
    .s3_hreadyout     (apb_periph_hreadyout),
    .s3_hresp         (apb_periph_hresp),
    .dbg_decode_error (dbg_matrix_decode_error)
  );

endmodule
